from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Optional
from datetime import datetime
from app.core.security import get_current_member, require_admin
from app.core.supabase_client import get_user_client, admin_client

router = APIRouter(prefix="/meetings", tags=["meetings"])


@router.get("")
def list_meetings(current=Depends(get_current_member)):
    client = get_user_client(current["token"])
    return client.table("meetings").select("*").order("meeting_date", desc=True).execute().data


class NewMeeting(BaseModel):
    title: str
    agenda: Optional[str] = None
    location: Optional[str] = None
    meeting_date: datetime


@router.post("/admin/create")
def create_meeting(payload: NewMeeting, current=Depends(get_current_member)):
    require_admin(current)
    client = get_user_client(current["token"])
    row = client.table("meetings").insert({
        **payload.model_dump(mode="json"),
        "created_by": current["member"]["id"],
    }).execute()
    # qr_code_token is auto-generated by the DB default; fetch it back
    meeting = row.data[0]
    return {**meeting, "qr_check_in_url": f"/meetings/check-in/{meeting['qr_code_token']}"}


@router.post("/check-in/{qr_token}")
def qr_check_in(qr_token: str, current=Depends(get_current_member)):
    """
    Called when a member scans the meeting's QR code (displayed on a
    screen/poster at the venue) using the app's in-built scanner.
    """
    client = get_user_client(current["token"])
    meeting = admin_client.table("meetings").select("id").eq(
        "qr_code_token", qr_token
    ).single().execute()
    if not meeting.data:
        raise HTTPException(404, "Invalid or expired QR code")

    try:
        client.table("meeting_attendance").insert({
            "meeting_id": meeting.data["id"],
            "member_id": current["member"]["id"],
        }).execute()
    except Exception:
        return {"message": "Attendance already recorded"}
    return {"message": "Attendance marked"}


@router.get("/{meeting_id}/attendance")
def meeting_attendance(meeting_id: str, current=Depends(get_current_member)):
    require_admin(current)
    client = get_user_client(current["token"])
    return client.table("meeting_attendance").select(
        "*, members(full_name, employee_id)"
    ).eq("meeting_id", meeting_id).execute().data
